-- MySQL Script generated by MySQL Workbench
-- Tue Feb 22 14:47:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cosybak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cosybak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cosybak` DEFAULT CHARACTER SET utf8 ;
USE `cosybak` ;

-- -----------------------------------------------------
-- Table `cosybak`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `user_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosybak`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `config_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_config1_idx` (`config_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cosybak`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `footer_order` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosybak`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT 'nom de la catégorie',
  `subtitle` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL DEFAULT 'L\'URL de l\'image de la catégorie (utilisée en home)',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosybak`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT 'nom du produit',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT 'la description du produit',
  `picture` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT 'l\'URL de l\'image produit',
  `price` DECIMAL NOT NULL DEFAULT 0 COMMENT 'Le prix du produit',
--   `rate` TINYINT NULL DEFAULT 'L\'avis sur le produit, de 1 à 5',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création du produit',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour du produit',
  `updated_at` TIMESTAMP NULL DEFAULT 'date de la dernière mise à jour',  
  `type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `category_id`),
  INDEX `fk_product_type1_idx` (`type_id` ASC),
  INDEX `fk_product_user1_idx` (`user_id` ASC),
  INDEX `fk_product_category1_idx` (`category_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosybak`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosybak`.`media` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `file` VARCHAR(45) NULL DEFAULT 'chemin vers le fichier',
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_media_product_idx` (`product_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Data for table `category`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `category` (`id`, `name`, `subtitle`, `picture`, `created_at`, `updated_at`) VALUES (1, 'Thés Bio', 'Découvrer notre gamme de thés verts-thés noirs ', 'images/categ1.jpeg','2022-02-22 8:00:00', NULL);
INSERT INTO `category` (`id`, `name`, `subtitle`, `picture`, `created_at`, `updated_at`) VALUES (2, 'Tisanes', 'Boisson saines et bienfaisantes', 'images/categ2.jpeg', '2022-02-22 8:00:00', NULL);
INSERT INTO `category` (`id`, `name`, `subtitle`, `picture`, `created_at`, `updated_at`) VALUES (3, 'Infusions', 'Des mélanges audacieux et délicieux', 'images/categ3.jpeg', '2022-02-22 8:00:00', NULL);
INSERT INTO `category` (`id`, `name`, `subtitle`, `picture`, `created_at`, `updated_at`) VALUES (4, 'Coffrets', 'Selection thés et infusion pour votre plaisir', 'images/categ4.jpeg', '2022-02-22 8:00:00', NULL);

COMMIT;